### ISSUE TITLE
Add `-c` or `--config` option`

### ISSUE THREAD

**Issue by Amnish04** [ijacobs-cpa/textml#12]
I would like to add support for a `--config` commandline argument to your project that takes a [TOML](https://toml.io/en/) file as input, and eliminates the need for users to type out all the options/flags manually.

I would likely be using a library called [Tomlib](https://github.com/hukkin/tomli#parse-a-toml-file) to parse the `TOML` files. If you don't have any issues, I can start working on it now.

**Comment by ijacobs-cpa** [comment]
Sounds good, go for it.
