### ISSUE TITLE
Help message improvement

### ISSUE THREAD

**Issue by mingming-ma** [ijacobs-cpa/textml#3]
https://github.com/ijacobs-cpa/textml/blob/293683d1d1c249dd9c2ede99d1c2d5bbf4bee81c/main.py#L93

Suggest to or similar 
```python
 print("Usage:\n python3 main.py <commands> [input-text-file|input-folder]\n")
```
as current tool only accept one text file for input, and also provide the folder as an input method

**Comment by ijacobs-cpa** [comment]
Issue fixed in the latest commit:

https://github.com/ijacobs-cpa/textml/blob/ec740e903aa10a8cb7e13ac5eddae413587e2b67/main.py#L93-L95
