### ISSUE TITLE
Document consistance  

### ISSUE THREAD

**Issue by mingming-ma** [ijacobs-cpa/textml#4]
https://github.com/ijacobs-cpa/textml/blob/293683d1d1c249dd9c2ede99d1c2d5bbf4bee81c/README.md?plain=1#L10

https://github.com/ijacobs-cpa/textml/blob/293683d1d1c249dd9c2ede99d1c2d5bbf4bee81c/README.md?plain=1#L22-L24

First code block has $ symbol but others not, also the second block maybe split in two command blocks.

**Comment by ijacobs-cpa** [comment]
Added consistent styling for install/run instructions in the readme  

Committed change: 854392f092455e931271f74c1c171eeb65463ec1
