### ISSUE TITLE
Code flexibility for future changes

### ISSUE THREAD

**Issue by mingming-ma** [ijacobs-cpa/textml#5]
https://github.com/ijacobs-cpa/textml/blob/293683d1d1c249dd9c2ede99d1c2d5bbf4bee81c/main.py#L15-L24

Here, we can change the 'textml' to a variable that holds that value for easy configuration and adaptation to different scenarios or user requirements.

**Comment by ijacobs-cpa** [comment]
Added and tested the updated defaultDirSetup for accepting different output directories.
https://github.com/ijacobs-cpa/textml/blob/7b019c56a8b3a13e862a5e1476b60c072139929b/main.py#L15-L24
